development: &default
  adapter: postgresql
  encoding: unicode
  database: docsync_dev
  host: localhost

test:
  <<: *default
  database: docsync_test

production:
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  url:  <%= ENV.fetch("DATABASE_URL") if Rails.env.production? %>
